package bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "comment".
 */
public class Comment {

    private String objectId;
    private Integer commnetId;
    private String commentAuthor;
    private String commentNote;
    private String commentInfo;
    private Integer commentType;
    private Integer commentState;
    private java.util.Date updadeAt;

    public Comment() {
    }

    public Comment(String objectId, Integer commnetId, String commentAuthor, String commentNote, String commentInfo, Integer commentType, Integer commentState, java.util.Date updadeAt) {
        this.objectId = objectId;
        this.commnetId = commnetId;
        this.commentAuthor = commentAuthor;
        this.commentNote = commentNote;
        this.commentInfo = commentInfo;
        this.commentType = commentType;
        this.commentState = commentState;
        this.updadeAt = updadeAt;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public Integer getCommnetId() {
        return commnetId;
    }

    public void setCommnetId(Integer commnetId) {
        this.commnetId = commnetId;
    }

    public String getCommentAuthor() {
        return commentAuthor;
    }

    public void setCommentAuthor(String commentAuthor) {
        this.commentAuthor = commentAuthor;
    }

    public String getCommentNote() {
        return commentNote;
    }

    public void setCommentNote(String commentNote) {
        this.commentNote = commentNote;
    }

    public String getCommentInfo() {
        return commentInfo;
    }

    public void setCommentInfo(String commentInfo) {
        this.commentInfo = commentInfo;
    }

    public Integer getCommentType() {
        return commentType;
    }

    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    public Integer getCommentState() {
        return commentState;
    }

    public void setCommentState(Integer commentState) {
        this.commentState = commentState;
    }

    public java.util.Date getUpdadeAt() {
        return updadeAt;
    }

    public void setUpdadeAt(java.util.Date updadeAt) {
        this.updadeAt = updadeAt;
    }

    @Override
    public String toString() {
        return "Comment[" +
                "commentAuthor='" + commentAuthor + '\'' +
                ", objectId='" + objectId + '\'' +
                ", commnetId=" + commnetId +
                ", commentNote='" + commentNote + '\'' +
                ", commentInfo='" + commentInfo + '\'' +
                ", commentType=" + commentType +
                ", commentState=" + commentState +
                ", updadeAt=" + updadeAt +
                ']';
    }
}
