package bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "note".
 */
public class Note {

    private String objectId;
    private Integer noteId;
    /** Not-null value. */
    private String noteAuthor;
    /** Not-null value. */
    private String noteTitle;
    /** Not-null value. */
    private String noteInfo;
    private int noteType;
    private String editSite;
    private java.util.Date updadeAt;

    public Note() {
    }

    public Note(String objectId, Integer noteId, String noteAuthor, String noteTitle, String noteInfo, int noteType, String editSite, java.util.Date updadeAt) {
        this.objectId = objectId;
        this.noteId = noteId;
        this.noteAuthor = noteAuthor;
        this.noteTitle = noteTitle;
        this.noteInfo = noteInfo;
        this.noteType = noteType;
        this.editSite = editSite;
        this.updadeAt = updadeAt;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public Integer getNoteId() {
        return noteId;
    }

    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }

    /** Not-null value. */
    public String getNoteAuthor() {
        return noteAuthor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNoteAuthor(String noteAuthor) {
        this.noteAuthor = noteAuthor;
    }

    /** Not-null value. */
    public String getNoteTitle() {
        return noteTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNoteTitle(String noteTitle) {
        this.noteTitle = noteTitle;
    }

    /** Not-null value. */
    public String getNoteInfo() {
        return noteInfo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNoteInfo(String noteInfo) {
        this.noteInfo = noteInfo;
    }

    public int getNoteType() {
        return noteType;
    }

    public void setNoteType(int noteType) {
        this.noteType = noteType;
    }

    public String getEditSite() {
        return editSite;
    }

    public void setEditSite(String editSite) {
        this.editSite = editSite;
    }

    public java.util.Date getUpdadeAt() {
        return updadeAt;
    }

    public void setUpdadeAt(java.util.Date updadeAt) {
        this.updadeAt = updadeAt;
    }

}
