package bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "user".
 */
public class User {

    private String objectId;
    private Integer userId;
    private String userSex;
    private String userCity;
    private Integer userAge;

    public User() {
    }

    public User(String objectId, Integer userId, String userSex, String userCity, Integer userAge) {
        this.objectId = objectId;
        this.userId = userId;
        this.userSex = userSex;
        this.userCity = userCity;
        this.userAge = userAge;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserSex() {
        return userSex;
    }

    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    public String getUserCity() {
        return userCity;
    }

    public void setUserCity(String userCity) {
        this.userCity = userCity;
    }

    public Integer getUserAge() {
        return userAge;
    }

    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

}
